# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
# images used by GenAIExamples: embedding-tei
services:
  embedding-tei:
    build:
      dockerfile: comps/embeddings/langchain/docker/Dockerfile
    image: ${REGISTRY}opea/embedding-tei:${TAG:-latest}
  embedding-langchain-mosec-endpoint:
    build:
      dockerfile: comps/embeddings/langchain-mosec/mosec-docker/Dockerfile
    image: ${REGISTRY}opea/embedding-langchain-mosec-endpoint:${TAG:-latest}
  embedding-langchain-mosec:
    build:
      dockerfile: comps/embeddings/langchain-mosec/docker/Dockerfile
    image: ${REGISTRY}opea/embedding-langchain-mosec:${TAG:-latest}
  embedding-tei-llama-index:
    build:
      dockerfile: comps/embeddings/llama_index/docker/Dockerfile
    image: ${REGISTRY}opea/embedding-tei-llama-index:${TAG:-latest}
